import { Request } from "./useRequests";

const generateDemoRequests = (): Request[] => {
  const today = new Date();
  const getDate = (daysAgo: number) => {
    const date = new Date(today);
    date.setDate(date.getDate() - daysAgo);
    return date.toISOString().split('T')[0];
  };

  return [
    {
      id: "demo-1",
      request_number: "2024-001",
      request_date: getDate(5),
      description: "Закупка офисного оборудования",
      status: "Доставлено",
      priority: "Плановая",
      applicant: "Иванов И.И.",
      executor: "Петров П.П.",
      availability_delivery_time: "5 рабочих дней",
      contractor: "ООО Поставщик",
      invoice_number: "СЧ-12345",
      amount: 125000,
      payment_percentage: 100,
      shipment_date: getDate(2),
      delivery_date: getDate(1),
      transport_company: "СДЭК",
      waybill_number: "ТТН-98765",
      comments: "Доставка выполнена в срок",
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(5),
      updated_at: getDate(1),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-2",
      request_number: "2024-002",
      request_date: getDate(3),
      description: "Срочный ремонт оборудования",
      status: "В работе",
      priority: "Аварийно",
      applicant: "Сидоров С.С.",
      executor: "Кузнецов К.К.",
      availability_delivery_time: "24 часа",
      contractor: "ООО Ремонт",
      invoice_number: "СЧ-12346",
      amount: 85000,
      payment_percentage: 50,
      shipment_date: getDate(1),
      delivery_date: null,
      transport_company: null,
      waybill_number: null,
      comments: "Требуется срочная замена комплектующих",
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(3),
      updated_at: getDate(0),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-3",
      request_number: "2024-003",
      request_date: getDate(0),
      description: "Новая заявка на расходные материалы",
      status: "Новая заявка",
      priority: "Плановая",
      applicant: "Морозова М.М.",
      executor: null,
      availability_delivery_time: null,
      contractor: null,
      invoice_number: null,
      amount: 0,
      payment_percentage: 0,
      shipment_date: null,
      delivery_date: null,
      transport_company: null,
      waybill_number: null,
      comments: null,
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(0),
      updated_at: getDate(0),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-4",
      request_number: "2024-004",
      request_date: getDate(7),
      description: "Закупка канцелярских товаров",
      status: "Счёт",
      priority: "Плановая",
      applicant: "Волкова В.В.",
      executor: "Соколов С.С.",
      availability_delivery_time: "3 рабочих дня",
      contractor: "ООО Канцтовары",
      invoice_number: "СЧ-12347",
      amount: 15500,
      payment_percentage: 30,
      shipment_date: null,
      delivery_date: null,
      transport_company: null,
      waybill_number: null,
      comments: "Ожидание оплаты счета",
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(7),
      updated_at: getDate(1),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-5",
      request_number: "2024-005",
      request_date: getDate(10),
      description: "Закупка мебели для нового офиса",
      status: "В пути",
      priority: "Срочно",
      applicant: "Николаев Н.Н.",
      executor: "Федоров Ф.Ф.",
      availability_delivery_time: "7 рабочих дней",
      contractor: "ООО Мебель",
      invoice_number: "СЧ-12348",
      amount: 245000,
      payment_percentage: 100,
      shipment_date: getDate(3),
      delivery_date: getDate(2),
      transport_company: "ПЭК",
      waybill_number: "ТТН-98766",
      comments: "В пути, ожидается доставка завтра",
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(10),
      updated_at: getDate(2),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-6",
      request_number: "2024-006",
      request_date: getDate(15),
      description: "Обновление программного обеспечения",
      status: "Доставлено",
      priority: "Плановая",
      applicant: "Александрова А.А.",
      executor: "Михайлов М.М.",
      availability_delivery_time: "1 рабочий день",
      contractor: "ООО Софт",
      invoice_number: "СЧ-12349",
      amount: 52000,
      payment_percentage: 100,
      shipment_date: getDate(14),
      delivery_date: getDate(14),
      transport_company: "Email доставка",
      waybill_number: null,
      comments: "Лицензии получены",
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(15),
      updated_at: getDate(14),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-7",
      request_number: "2024-007",
      request_date: getDate(2),
      description: "Аварийная закупка комплектующих",
      status: "КП",
      priority: "Аварийно",
      applicant: "Дмитриев Д.Д.",
      executor: "Павлов П.П.",
      availability_delivery_time: "Срочно",
      contractor: null,
      invoice_number: null,
      amount: 0,
      payment_percentage: 0,
      shipment_date: null,
      delivery_date: null,
      transport_company: null,
      waybill_number: null,
      comments: "Ожидание коммерческого предложения",
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(2),
      updated_at: getDate(1),
      archived: false,
      client_id: null,
    },
    {
      id: "demo-8",
      request_number: "2024-008",
      request_date: getDate(20),
      description: "Закупка расходных материалов для принтера",
      status: "Доставлено",
      priority: "Плановая",
      applicant: "Егорова Е.Е.",
      executor: "Семенов С.С.",
      availability_delivery_time: "2 рабочих дня",
      contractor: "ООО Принтеры",
      invoice_number: "СЧ-12350",
      amount: 32500,
      payment_percentage: 100,
      shipment_date: getDate(18),
      delivery_date: getDate(17),
      transport_company: "Boxberry",
      waybill_number: "ТТН-98767",
      comments: null,
      photo_url: null,
      document_url: null,
      organization_id: null,
      created_at: getDate(20),
      updated_at: getDate(17),
      archived: false,
      client_id: null,
    },
  ];
};

export const useDemoData = () => {
  const demoRequests = generateDemoRequests();

  const getDemoStats = () => {
    const today = new Date().toISOString().split("T")[0];
    return {
      total: demoRequests.length,
      newToday: demoRequests.filter(r => r.created_at?.split("T")[0] === today).length,
      emergency: demoRequests.filter(r => r.priority === "Аварийно").length,
      completed: demoRequests.filter(r => r.status === "Доставлено").length,
    };
  };

  return {
    requests: demoRequests,
    stats: getDemoStats(),
  };
};
