// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-requests.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_requests_default = defineTool({
  name: "list_requests",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A \u0437\u0430\u044F\u0432\u043E\u043A",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0441\u043F\u0438\u0441\u043E\u043A \u0437\u0430\u044F\u0432\u043E\u043A (\u0441\u043D\u0430\u0431\u0436\u0435\u043D\u0438\u0435) \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u0438 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F. \u041F\u043E\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u0442 \u0444\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u0441\u0442\u0430\u0442\u0443\u0441\u0443, \u043F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442\u0443, \u043F\u043E\u0438\u0441\u043A\u043E\u0432\u043E\u0439 \u0441\u0442\u0440\u043E\u043A\u0435 \u0438 \u043B\u0438\u043C\u0438\u0442.",
  inputSchema: {
    status: z.string().optional().describe("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u0441\u0442\u0430\u0442\u0443\u0441\u0443, \u043D\u0430\u043F\u0440. '\u0412 \u0440\u0430\u0431\u043E\u0442\u0435', '\u0414\u043E\u0441\u0442\u0430\u0432\u043B\u0435\u043D\u043E'."),
    priority: z.string().optional().describe("\u0424\u0438\u043B\u044C\u0442\u0440 \u043F\u043E \u043F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442\u0443: '\u0410\u0432\u0430\u0440\u0438\u0439\u043D\u043E', '\u041F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442\u043D\u043E', '\u041F\u043B\u0430\u043D\u043E\u0432\u043E'."),
    search: z.string().optional().describe("\u041F\u043E\u0438\u0441\u043A \u043F\u043E \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u044E/\u043A\u043E\u043D\u0442\u0440\u0430\u0433\u0435\u043D\u0442\u0443."),
    archived: z.boolean().optional().describe("\u041F\u043E\u043A\u0430\u0437\u044B\u0432\u0430\u0442\u044C \u0430\u0440\u0445\u0438\u0432\u043D\u044B\u0435 (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E false)."),
    limit: z.number().int().min(1).max(100).optional().describe("\u041C\u0430\u043A\u0441\u0438\u043C\u0443\u043C \u0437\u0430\u043F\u0438\u0441\u0435\u0439 (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, priority, search, archived, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u041D\u0435 \u0430\u0432\u0442\u043E\u0440\u0438\u0437\u043E\u0432\u0430\u043D" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("requests").select(
      "id,request_number,request_date,description,status,priority,contractor,executor,applicant,amount,delivery_date,archived"
    ).eq("archived", archived ?? false).order("request_date", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (priority) q = q.eq("priority", priority);
    if (search) q = q.or(`description.ilike.%${search}%,contractor.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `\u041E\u0448\u0438\u0431\u043A\u0430: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { requests: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-request.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_request_default = defineTool2({
  name: "get_request",
  title: "\u0414\u0435\u0442\u0430\u043B\u0438 \u0437\u0430\u044F\u0432\u043A\u0438",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u043F\u043E\u043B\u043D\u0443\u044E \u043A\u0430\u0440\u0442\u043E\u0447\u043A\u0443 \u0437\u0430\u044F\u0432\u043A\u0438 \u043F\u043E \u0435\u0451 id: \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u0435, \u0441\u0442\u0430\u0442\u0443\u0441, \u0441\u0443\u043C\u043C\u044B, \u043A\u043E\u043D\u0442\u0440\u0430\u0433\u0435\u043D\u0442, \u0434\u0430\u0442\u044B \u043E\u0442\u0433\u0440\u0443\u0437\u043A\u0438/\u0434\u043E\u0441\u0442\u0430\u0432\u043A\u0438, \u043A\u043E\u043C\u043C\u0435\u043D\u0442\u0430\u0440\u0438\u0438.",
  inputSchema: {
    request_id: z2.string().uuid().describe("UUID \u0437\u0430\u044F\u0432\u043A\u0438.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ request_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u041D\u0435 \u0430\u0432\u0442\u043E\u0440\u0438\u0437\u043E\u0432\u0430\u043D" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("requests").select("*").eq("id", request_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `\u041E\u0448\u0438\u0431\u043A\u0430: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "\u0417\u0430\u044F\u0432\u043A\u0430 \u043D\u0435 \u043D\u0430\u0439\u0434\u0435\u043D\u0430 \u0438\u043B\u0438 \u043D\u0435\u0442 \u0434\u043E\u0441\u0442\u0443\u043F\u0430." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { request: data }
    };
  }
});

// src/lib/mcp/tools/list-my-planner-tasks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_planner_tasks_default = defineTool3({
  name: "list_my_planner_tasks",
  title: "\u041C\u043E\u0438 \u0437\u0430\u0434\u0430\u0447\u0438 \u043F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0449\u0438\u043A\u0430",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u0437\u0430\u0434\u0430\u0447\u0438 \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u043B\u044C\u043D\u043E\u0433\u043E \u043F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0449\u0438\u043A\u0430 \u0442\u0435\u043A\u0443\u0449\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F. \u041C\u043E\u0436\u043D\u043E \u043E\u0442\u0444\u0438\u043B\u044C\u0442\u0440\u043E\u0432\u0430\u0442\u044C \u043F\u043E \u0441\u0442\u0430\u0442\u0443\u0441\u0443 \u0438 \u0434\u0438\u0430\u043F\u0430\u0437\u043E\u043D\u0443 'today'/'upcoming'/'overdue'/'all'.",
  inputSchema: {
    status: z3.string().optional().describe("\u0421\u0442\u0430\u0442\u0443\u0441 \u0437\u0430\u0434\u0430\u0447\u0438: 'todo', 'in_progress', 'done' \u0438 \u0442.\u043F."),
    scope: z3.enum(["today", "upcoming", "overdue", "all"]).optional().describe("\u0412\u0440\u0435\u043C\u0435\u043D\u043D\u043E\u0439 \u0441\u0440\u0435\u0437: \u0441\u0435\u0433\u043E\u0434\u043D\u044F/\u0431\u043B\u0438\u0436\u0430\u0439\u0448\u0438\u0435/\u043F\u0440\u043E\u0441\u0440\u043E\u0447\u0435\u043D\u043D\u044B\u0435/\u0432\u0441\u0435."),
    limit: z3.number().int().min(1).max(100).optional().describe("\u041C\u0430\u043A\u0441\u0438\u043C\u0443\u043C \u0437\u0430\u043F\u0438\u0441\u0435\u0439 (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, scope, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u041D\u0435 \u0430\u0432\u0442\u043E\u0440\u0438\u0437\u043E\u0432\u0430\u043D" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    const uid = ctx.getUserId();
    let q = sb.from("planner_tasks").select("id,title,description,status,priority,due_date,start_date,tags,object_id,assignee_id,created_by").or(`assignee_id.eq.${uid},created_by.eq.${uid}`).order("due_date", { ascending: true, nullsFirst: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const now = /* @__PURE__ */ new Date();
    const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();
    const endOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1).toISOString();
    if (scope === "today") {
      q = q.gte("due_date", startOfToday).lt("due_date", endOfToday);
    } else if (scope === "upcoming") {
      q = q.gte("due_date", endOfToday);
    } else if (scope === "overdue") {
      q = q.lt("due_date", startOfToday).neq("status", "done");
    }
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `\u041E\u0448\u0438\u0431\u043A\u0430: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { tasks: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/create-planner-task.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_planner_task_default = defineTool4({
  name: "create_planner_task",
  title: "\u0421\u043E\u0437\u0434\u0430\u0442\u044C \u0437\u0430\u0434\u0430\u0447\u0443 \u0432 \u043F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0449\u0438\u043A\u0435",
  description: "\u0421\u043E\u0437\u0434\u0430\u0451\u0442 \u043D\u043E\u0432\u0443\u044E \u0437\u0430\u0434\u0430\u0447\u0443 \u0432 \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u043B\u044C\u043D\u043E\u043C \u043F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0449\u0438\u043A\u0435 \u0442\u0435\u043A\u0443\u0449\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F (\u043D\u0430\u0437\u043D\u0430\u0447\u0430\u0435\u0442\u0441\u044F \u0435\u043C\u0443 \u0436\u0435).",
  inputSchema: {
    title: z4.string().trim().min(1).max(500).describe("\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435 \u0437\u0430\u0434\u0430\u0447\u0438."),
    description: z4.string().max(5e3).optional().describe("\u041F\u043E\u0434\u0440\u043E\u0431\u043D\u043E\u0435 \u043E\u043F\u0438\u0441\u0430\u043D\u0438\u0435."),
    due_date: z4.string().datetime({ offset: true }).optional().describe("ISO-\u0434\u0430\u0442\u0430 \u0434\u0435\u0434\u043B\u0430\u0439\u043D\u0430, \u043D\u0430\u043F\u0440. '2026-07-10T15:00:00Z'."),
    priority: z4.enum(["low", "medium", "high", "urgent"]).optional().describe("\u041F\u0440\u0438\u043E\u0440\u0438\u0442\u0435\u0442."),
    tags: z4.array(z4.string()).max(20).optional().describe("\u041C\u0435\u0442\u043A\u0438.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, description, due_date, priority, tags }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u041D\u0435 \u0430\u0432\u0442\u043E\u0440\u0438\u0437\u043E\u0432\u0430\u043D" }], isError: true };
    }
    const sb = supabaseForUser4(ctx);
    const uid = ctx.getUserId();
    const { data: org, error: orgErr } = await sb.from("user_organizations").select("organization_id").eq("user_id", uid).limit(1).maybeSingle();
    if (orgErr || !org) {
      return {
        content: [{ type: "text", text: "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u043E\u043F\u0440\u0435\u0434\u0435\u043B\u0438\u0442\u044C \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u044E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F." }],
        isError: true
      };
    }
    const { data, error } = await sb.from("planner_tasks").insert({
      organization_id: org.organization_id,
      title,
      description: description ?? null,
      due_date: due_date ?? null,
      priority: priority ?? "medium",
      tags: tags ?? [],
      status: "todo",
      assignee_id: uid,
      created_by: uid,
      source: "mcp"
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: `\u041E\u0448\u0438\u0431\u043A\u0430: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `\u0417\u0430\u0434\u0430\u0447\u0430 \u0441\u043E\u0437\u0434\u0430\u043D\u0430: ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-objects.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.23.8";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_objects_default = defineTool5({
  name: "list_objects",
  title: "\u0421\u043F\u0438\u0441\u043E\u043A \u043E\u0431\u044A\u0435\u043A\u0442\u043E\u0432",
  description: "\u0412\u043E\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 \u043E\u0431\u044A\u0435\u043A\u0442\u044B (\u0441\u0442\u0440\u043E\u0439\u043F\u043B\u043E\u0449\u0430\u0434\u043A\u0438/\u0441\u043A\u043B\u0430\u0434\u044B) \u043E\u0440\u0433\u0430\u043D\u0438\u0437\u0430\u0446\u0438\u0438 \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F. \u041F\u043E\u043B\u0435\u0437\u043D\u043E \u0434\u043B\u044F \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430 \u043F\u0440\u0438 \u0441\u043E\u0437\u0434\u0430\u043D\u0438\u0438 \u0437\u0430\u0434\u0430\u0447/\u0437\u0430\u044F\u0432\u043E\u043A.",
  inputSchema: {
    search: z5.string().optional().describe("\u041F\u043E\u0438\u0441\u043A \u043F\u043E \u0438\u043C\u0435\u043D\u0438 \u043E\u0431\u044A\u0435\u043A\u0442\u0430."),
    limit: z5.number().int().min(1).max(200).optional().describe("\u041C\u0430\u043A\u0441\u0438\u043C\u0443\u043C \u0437\u0430\u043F\u0438\u0441\u0435\u0439 (\u043F\u043E \u0443\u043C\u043E\u043B\u0447\u0430\u043D\u0438\u044E 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "\u041D\u0435 \u0430\u0432\u0442\u043E\u0440\u0438\u0437\u043E\u0432\u0430\u043D" }], isError: true };
    }
    const sb = supabaseForUser5(ctx);
    let q = sb.from("request_objects").select("id,name,address,status").order("name", { ascending: true }).limit(limit ?? 50);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `\u041E\u0448\u0438\u0431\u043A\u0430: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { objects: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cfdwsdydbtwaljnidirf";
var mcp_default = defineMcp({
  name: "crss-snab-mcp",
  title: "CRSS \u0421\u043D\u0430\u0431 \u2014 Agent Integration",
  version: "0.1.0",
  instructions: "\u0418\u043D\u0441\u0442\u0440\u0443\u043C\u0435\u043D\u0442\u044B CRSS \u0421\u043D\u0430\u0431 \u0434\u043B\u044F AI-\u0430\u0441\u0441\u0438\u0441\u0442\u0435\u043D\u0442\u043E\u0432. \u0418\u0441\u043F\u043E\u043B\u044C\u0437\u0443\u0439\u0442\u0435 list_requests / get_request \u0434\u043B\u044F \u0440\u0430\u0431\u043E\u0442\u044B \u0441 \u0437\u0430\u044F\u0432\u043A\u0430\u043C\u0438 \u0441\u043D\u0430\u0431\u0436\u0435\u043D\u0438\u044F, list_objects \u0434\u043B\u044F \u043A\u043E\u043D\u0442\u0435\u043A\u0441\u0442\u0430 \u043E\u0431\u044A\u0435\u043A\u0442\u043E\u0432, list_my_planner_tasks \u0438 create_planner_task \u2014 \u0434\u043B\u044F \u043F\u0435\u0440\u0441\u043E\u043D\u0430\u043B\u044C\u043D\u043E\u0433\u043E \u043F\u043B\u0430\u043D\u0438\u0440\u043E\u0432\u0449\u0438\u043A\u0430 \u0442\u0435\u043A\u0443\u0449\u0435\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F. \u0412\u0441\u0435 \u043E\u043F\u0435\u0440\u0430\u0446\u0438\u0438 \u0432\u044B\u043F\u043E\u043B\u043D\u044F\u044E\u0442\u0441\u044F \u043E\u0442 \u0438\u043C\u0435\u043D\u0438 \u0437\u0430\u043B\u043E\u0433\u0438\u043D\u0435\u043D\u043D\u043E\u0433\u043E \u043F\u043E\u043B\u044C\u0437\u043E\u0432\u0430\u0442\u0435\u043B\u044F \u0438 \u0443\u0432\u0430\u0436\u0430\u044E\u0442 \u0435\u0433\u043E \u043F\u0440\u0430\u0432\u0430 \u0434\u043E\u0441\u0442\u0443\u043F\u0430.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_requests_default,
    get_request_default,
    list_objects_default,
    list_my_planner_tasks_default,
    create_planner_task_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
