UPDATE public.material_statement_items
SET item_type = 'work'
WHERE item_type = 'material'
  AND (
    lower(name) LIKE '%монтаж%'
    OR lower(name) LIKE '%устройство%'
    OR lower(name) LIKE '%установка%'
    OR lower(name) LIKE '%сборка%'
    OR lower(name) LIKE '%укладка%'
    OR lower(name) LIKE '%демонтаж%'
    OR lower(name) LIKE '%прокладка%'
    OR lower(name) LIKE '%подключение%'
    OR lower(name) LIKE '%наладка%'
    OR lower(name) LIKE '%испытание%'
    OR lower(name) LIKE '%пуск%'
    OR lower(name) LIKE '%разборка%'
    OR lower(name) LIKE '%ремонт%'
    OR lower(name) LIKE '%замена%'
    OR lower(name) LIKE '%окраска%'
    OR lower(name) LIKE '%грунтовка%'
    OR lower(name) LIKE '%штукатурка%'
    OR lower(name) LIKE '%бетонирование%'
    OR lower(name) LIKE '%армирование%'
    OR lower(name) LIKE '%сварка%'
    OR lower(name) LIKE '%изоляция%'
    OR lower(name) LIKE '%утепление%'
    OR lower(name) LIKE '%облицовка%'
    OR lower(name) LIKE '%отделка%'
  )